[2022-04-28  22:27:21.972] -> [WARNING]: 
warning
[2022-04-28  22:27:21.977] -> [ERROR]: 
error
[2022-04-28  22:27:21.981] -> [CRITICAL]: 
critical
[2022-04-28  22:27:21.982] -> [DEBUG]: 
debug
[2022-04-28  22:27:21.987] -> [INFO]: 
info
[2022-04-28  22:27:21.991] -> [WARNING]: 
warning
[2022-04-28  22:27:21.992] -> [ERROR]: 
error
[2022-04-28  22:27:21.993] -> [CRITICAL]: 
critical
[2022-04-28  22:32:12.706] -> [ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:32:12.721] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:32:12.724] -> [DEBUG]: 
1
[2022-04-28  22:32:12.735] -> [DEBUG]: 
2
[2022-04-28  22:41:30.104] -> [ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:41:30.122] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:41:30.123] -> [DEBUG]: 
debug
[2022-04-28  22:41:30.124] -> [INFO]: 
info
[2022-04-28  22:41:30.128] -> [WARNING]: 
warning
[2022-04-28  22:41:30.129] -> [ERROR]: 
error
[2022-04-28  22:41:30.132] -> [CRITICAL]: 
critical
[2022-04-28  22:41:30.134] -> [DEBUG]: 
debug
[2022-04-28  22:41:30.136] -> [INFO]: 
info
[2022-04-28  22:41:30.140] -> [WARNING]: 
warning
[2022-04-28  22:41:30.142] -> [ERROR]: 
error
[2022-04-28  22:41:30.145] -> [CRITICAL]: 
critical
[2022-04-28  22:41:30.147] -> [DEBUG]: 
debug
[2022-04-28  22:41:30.152] -> [INFO]: 
info
[2022-04-28  22:41:30.155] -> [WARNING]: 
warning
[2022-04-28  22:41:30.159] -> [ERROR]: 
error
[2022-04-28  22:41:30.167] -> [CRITICAL]: 
critical
[2022-04-28  22:41:30.177] -> [DEBUG]: 
debug
[2022-04-28  22:41:30.183] -> [INFO]: 
info
[2022-04-28  22:41:30.196] -> [WARNING]: 
warning
[2022-04-28  22:41:30.201] -> [ERROR]: 
error
[2022-04-28  22:41:30.227] -> [CRITICAL]: 
critical
[2022-04-28  22:41:30.246] -> [DEBUG]: 
debug
[2022-04-28  22:41:30.248] -> [INFO]: 
info
[2022-04-28  22:41:30.251] -> [WARNING]: 
warning
[2022-04-28  22:41:30.385] -> [ERROR]: 
error
[2022-04-28  22:41:30.398] -> [CRITICAL]: 
critical
[2022-04-28  22:41:30.715] -> [CRITICAL]: 
NoneType: None

[2022-04-28  22:41:30.833] -> [CRITICAL]: 
Traceback (most recent call last):
  File "c:/Users/admin/Documents/Python/QGMA_GIT/qgma-1/core/log.py", line 174, in <module>
    logger.debug(Handle_Log.Get_Error())
  File "c:/Users/admin/Documents/Python/QGMA_GIT/qgma-1/core/log.py", line 113, in Get_Error
    quit()
  File "C:\Program Files (x86)\Python38-32\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

[2022-04-28  22:42:14.361] -> [ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:42:14.394] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:42:14.397] -> [DEBUG]: 
debug
[2022-04-28  22:42:14.404] -> [INFO]: 
info
[2022-04-28  22:42:14.413] -> [WARNING]: 
warning
[2022-04-28  22:42:14.459] -> [ERROR]: 
error
[2022-04-28  22:42:14.541] -> [CRITICAL]: 
critical
[2022-04-28  22:42:14.588] -> [DEBUG]: 
debug
[2022-04-28  22:42:14.747] -> [INFO]: 
info
[2022-04-28  22:42:14.842] -> [WARNING]: 
warning
[2022-04-28  22:42:14.893] -> [ERROR]: 
error
[2022-04-28  22:42:14.898] -> [CRITICAL]: 
critical
[2022-04-28  22:42:14.906] -> [DEBUG]: 
debug
[2022-04-28  22:42:14.909] -> [INFO]: 
info
[2022-04-28  22:42:14.913] -> [WARNING]: 
warning
[2022-04-28  22:42:15.015] -> [ERROR]: 
error
[2022-04-28  22:42:15.025] -> [CRITICAL]: 
critical
[2022-04-28  22:42:15.186] -> [DEBUG]: 
debug
[2022-04-28  22:42:15.200] -> [INFO]: 
info
[2022-04-28  22:42:15.224] -> [WARNING]: 
warning
[2022-04-28  22:42:15.229] -> [ERROR]: 
error
[2022-04-28  22:42:15.232] -> [CRITICAL]: 
critical
[2022-04-28  22:42:15.322] -> [DEBUG]: 
debug
[2022-04-28  22:42:15.330] -> [INFO]: 
info
[2022-04-28  22:42:15.417] -> [WARNING]: 
warning
[2022-04-28  22:42:15.496] -> [ERROR]: 
error
[2022-04-28  22:42:15.505] -> [CRITICAL]: 
critical
[2022-04-28  22:42:15.617] -> [INFO]: 
ok
[2022-04-28  22:42:15.796] -> [CRITICAL]: 
NoneType: None

[2022-04-28  22:42:15.807] -> [CRITICAL]: 
Traceback (most recent call last):
  File "c:/Users/admin/Documents/Python/QGMA_GIT/qgma-1/core/log.py", line 175, in <module>
    logger.debug(Handle_Log.Get_Error())
  File "c:/Users/admin/Documents/Python/QGMA_GIT/qgma-1/core/log.py", line 113, in Get_Error
    quit()
  File "C:\Program Files (x86)\Python38-32\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

[2022-04-28  22:44:27.685] -> [ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:44:27.807] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:44:28.169] -> [DEBUG]: 
debug
[2022-04-28  22:44:28.292] -> [INFO]: 
info
[2022-04-28  22:44:28.379] -> [WARNING]: 
warning
[2022-04-28  22:44:28.597] -> [ERROR]: 
error
[2022-04-28  22:44:28.685] -> [CRITICAL]: 
critical
[2022-04-28  22:44:28.886] -> [DEBUG]: 
debug
[2022-04-28  22:44:28.902] -> [INFO]: 
info
[2022-04-28  22:44:29.072] -> [WARNING]: 
warning
[2022-04-28  22:44:29.082] -> [ERROR]: 
error
[2022-04-28  22:44:29.263] -> [CRITICAL]: 
critical
[2022-04-28  22:44:29.392] -> [DEBUG]: 
debug
[2022-04-28  22:44:29.595] -> [INFO]: 
info
[2022-04-28  22:44:29.725] -> [WARNING]: 
warning
[2022-04-28  22:44:29.871] -> [ERROR]: 
error
[2022-04-28  22:44:29.882] -> [CRITICAL]: 
critical
[2022-04-28  22:44:30.047] -> [DEBUG]: 
debug
[2022-04-28  22:44:30.055] -> [INFO]: 
info
[2022-04-28  22:44:30.066] -> [WARNING]: 
warning
[2022-04-28  22:44:30.072] -> [ERROR]: 
error
[2022-04-28  22:44:30.074] -> [CRITICAL]: 
critical
[2022-04-28  22:44:30.163] -> [DEBUG]: 
debug
[2022-04-28  22:44:30.386] -> [INFO]: 
info
[2022-04-28  22:44:30.559] -> [WARNING]: 
warning
[2022-04-28  22:44:30.875] -> [ERROR]: 
error
[2022-04-28  22:44:30.963] -> [CRITICAL]: 
critical
[2022-04-28  22:44:31.218] -> [INFO]: 
ok
[2022-04-28  22:44:31.223] -> [CRITICAL]: 
NoneType: None

[2022-04-28  22:44:31.236] -> [CRITICAL]: 
Traceback (most recent call last):
  File "c:/Users/admin/Documents/Python/QGMA_GIT/qgma-1/core/log.py", line 175, in <module>
    logger.debug(Handle_Log.Get_Error())
  File "c:/Users/admin/Documents/Python/QGMA_GIT/qgma-1/core/log.py", line 113, in Get_Error
    quit()
  File "C:\Program Files (x86)\Python38-32\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

[2022-04-28  22:45:05.345] -> [ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:45:05.377] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:45:05.415] -> [DEBUG]: 
debug
[2022-04-28  22:45:05.425] -> [INFO]: 
info
[2022-04-28  22:45:05.615] -> [WARNING]: 
warning
[2022-04-28  22:45:05.630] -> [ERROR]: 
error
[2022-04-28  22:45:05.816] -> [CRITICAL]: 
critical
[2022-04-28  22:45:05.853] -> [DEBUG]: 
debug
[2022-04-28  22:45:06.008] -> [INFO]: 
info
[2022-04-28  22:45:06.072] -> [WARNING]: 
warning
[2022-04-28  22:45:06.309] -> [ERROR]: 
error
[2022-04-28  22:45:06.573] -> [CRITICAL]: 
critical
[2022-04-28  22:45:06.859] -> [DEBUG]: 
debug
[2022-04-28  22:45:07.039] -> [INFO]: 
info
[2022-04-28  22:45:07.454] -> [WARNING]: 
warning
[2022-04-28  22:45:07.607] -> [ERROR]: 
error
[2022-04-28  22:45:07.616] -> [CRITICAL]: 
critical
[2022-04-28  22:45:07.621] -> [DEBUG]: 
debug
[2022-04-28  22:45:07.758] -> [INFO]: 
info
[2022-04-28  22:45:07.805] -> [WARNING]: 
warning
[2022-04-28  22:45:07.963] -> [ERROR]: 
error
[2022-04-28  22:45:08.013] -> [CRITICAL]: 
critical
[2022-04-28  22:45:08.018] -> [DEBUG]: 
debug
[2022-04-28  22:45:08.193] -> [INFO]: 
info
[2022-04-28  22:45:08.220] -> [WARNING]: 
warning
[2022-04-28  22:45:08.322] -> [ERROR]: 
error
[2022-04-28  22:45:08.355] -> [CRITICAL]: 
critical
[2022-04-28  22:45:08.455] -> [CRITICAL]: 
Traceback (most recent call last):
  File "c:/Users/admin/Documents/Python/QGMA_GIT/qgma-1/core/log.py", line 175, in <module>
    p
NameError: name 'p' is not defined

[2022-04-28  22:45:39.750] -> [ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:45:39.757] -> [DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:45:39.758] -> [DEBUG]: 
debug
[2022-04-28  22:45:39.762] -> [INFO]: 
info
[2022-04-28  22:45:39.763] -> [WARNING]: 
warning
[2022-04-28  22:45:39.766] -> [ERROR]: 
error
[2022-04-28  22:45:39.768] -> [CRITICAL]: 
critical
[2022-04-28  22:45:39.772] -> [DEBUG]: 
debug
[2022-04-28  22:45:39.775] -> [INFO]: 
info
[2022-04-28  22:45:39.783] -> [WARNING]: 
warning
[2022-04-28  22:45:39.787] -> [ERROR]: 
error
[2022-04-28  22:45:39.791] -> [CRITICAL]: 
critical
[2022-04-28  22:45:39.797] -> [DEBUG]: 
debug
[2022-04-28  22:45:39.801] -> [INFO]: 
info
[2022-04-28  22:45:39.803] -> [WARNING]: 
warning
[2022-04-28  22:45:39.805] -> [ERROR]: 
error
[2022-04-28  22:45:39.807] -> [CRITICAL]: 
critical
[2022-04-28  22:45:39.864] -> [DEBUG]: 
debug
[2022-04-28  22:45:40.008] -> [INFO]: 
info
[2022-04-28  22:45:40.229] -> [WARNING]: 
warning
[2022-04-28  22:45:40.315] -> [ERROR]: 
error
[2022-04-28  22:45:40.427] -> [CRITICAL]: 
critical
[2022-04-28  22:45:40.540] -> [DEBUG]: 
debug
[2022-04-28  22:45:40.651] -> [INFO]: 
info
[2022-04-28  22:45:40.714] -> [WARNING]: 
warning
[2022-04-28  22:45:40.756] -> [ERROR]: 
error
[2022-04-28  22:45:40.847] -> [CRITICAL]: 
critical
[2022-04-28  22:45:40.947] -> [CRITICAL]: 
NoneType: None

[2022-04-28  22:47:16460]->[ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:47:16465]->[DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:47:16469]->[DEBUG]: 
debug
[2022-04-28  22:47:16471]->[INFO]: 
info
[2022-04-28  22:47:16475]->[WARNING]: 
warning
[2022-04-28  22:47:16491]->[ERROR]: 
error
[2022-04-28  22:47:16517]->[CRITICAL]: 
critical
[2022-04-28  22:47:16648]->[DEBUG]: 
debug
[2022-04-28  22:47:16663]->[INFO]: 
info
[2022-04-28  22:47:16753]->[WARNING]: 
warning
[2022-04-28  22:47:16859]->[ERROR]: 
error
[2022-04-28  22:47:16870]->[CRITICAL]: 
critical
[2022-04-28  22:47:16884]->[DEBUG]: 
debug
[2022-04-28  22:47:16974]->[INFO]: 
info
[2022-04-28  22:47:16977]->[WARNING]: 
warning
[2022-04-28  22:47:16981]->[ERROR]: 
error
[2022-04-28  22:47:17027]->[CRITICAL]: 
critical
[2022-04-28  22:47:17091]->[DEBUG]: 
debug
[2022-04-28  22:47:17113]->[INFO]: 
info
[2022-04-28  22:47:17172]->[WARNING]: 
warning
[2022-04-28  22:47:17222]->[ERROR]: 
error
[2022-04-28  22:47:17235]->[CRITICAL]: 
critical
[2022-04-28  22:47:17239]->[DEBUG]: 
debug
[2022-04-28  22:47:17242]->[INFO]: 
info
[2022-04-28  22:47:17245]->[WARNING]: 
warning
[2022-04-28  22:47:17247]->[ERROR]: 
error
[2022-04-28  22:47:17437]->[CRITICAL]: 
critical
[2022-04-28  22:47:17454]->[CRITICAL]: 
NoneType: None

[2022-04-28  22:47:43.734]->[ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:47:43.741]->[DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:47:43.744]->[DEBUG]: 
debug
[2022-04-28  22:47:43.748]->[INFO]: 
info
[2022-04-28  22:47:43.753]->[WARNING]: 
warning
[2022-04-28  22:47:43.757]->[ERROR]: 
error
[2022-04-28  22:47:43.761]->[CRITICAL]: 
critical
[2022-04-28  22:47:43.763]->[DEBUG]: 
debug
[2022-04-28  22:47:43.766]->[INFO]: 
info
[2022-04-28  22:47:43.772]->[WARNING]: 
warning
[2022-04-28  22:47:43.776]->[ERROR]: 
error
[2022-04-28  22:47:43.780]->[CRITICAL]: 
critical
[2022-04-28  22:47:43.782]->[DEBUG]: 
debug
[2022-04-28  22:47:43.785]->[INFO]: 
info
[2022-04-28  22:47:43.788]->[WARNING]: 
warning
[2022-04-28  22:47:43.790]->[ERROR]: 
error
[2022-04-28  22:47:43.792]->[CRITICAL]: 
critical
[2022-04-28  22:47:43.798]->[DEBUG]: 
debug
[2022-04-28  22:47:43.801]->[INFO]: 
info
[2022-04-28  22:47:43.802]->[WARNING]: 
warning
[2022-04-28  22:47:43.809]->[ERROR]: 
error
[2022-04-28  22:47:43.920]->[CRITICAL]: 
critical
[2022-04-28  22:47:43.927]->[DEBUG]: 
debug
[2022-04-28  22:47:43.929]->[INFO]: 
info
[2022-04-28  22:47:43.933]->[WARNING]: 
warning
[2022-04-28  22:47:43.953]->[ERROR]: 
error
[2022-04-28  22:47:43.965]->[CRITICAL]: 
critical
[2022-04-28  22:47:43.972]->[CRITICAL]: 
NoneType: None

[2022-04-28  22:47:49.994]->[ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:47:50.005]->[DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:47:50.008]->[DEBUG]: 
debug
[2022-04-28  22:47:50.011]->[INFO]: 
info
[2022-04-28  22:47:50.012]->[WARNING]: 
warning
[2022-04-28  22:47:50.016]->[ERROR]: 
error
[2022-04-28  22:47:50.105]->[CRITICAL]: 
critical
[2022-04-28  22:47:50.159]->[DEBUG]: 
debug
[2022-04-28  22:47:50.163]->[INFO]: 
info
[2022-04-28  22:47:50.165]->[WARNING]: 
warning
[2022-04-28  22:47:50.167]->[ERROR]: 
error
[2022-04-28  22:47:50.174]->[CRITICAL]: 
critical
[2022-04-28  22:47:50.176]->[DEBUG]: 
debug
[2022-04-28  22:47:50.229]->[INFO]: 
info
[2022-04-28  22:47:50.248]->[WARNING]: 
warning
[2022-04-28  22:47:50.256]->[ERROR]: 
error
[2022-04-28  22:47:50.286]->[CRITICAL]: 
critical
[2022-04-28  22:47:50.400]->[DEBUG]: 
debug
[2022-04-28  22:47:50.424]->[INFO]: 
info
[2022-04-28  22:47:50.465]->[WARNING]: 
warning
[2022-04-28  22:47:50.564]->[ERROR]: 
error
[2022-04-28  22:47:50.567]->[CRITICAL]: 
critical
[2022-04-28  22:47:50.570]->[DEBUG]: 
debug
[2022-04-28  22:47:50.581]->[INFO]: 
info
[2022-04-28  22:47:50.662]->[WARNING]: 
warning
[2022-04-28  22:47:50.677]->[ERROR]: 
error
[2022-04-28  22:47:50.802]->[CRITICAL]: 
critical
[2022-04-28  22:47:50.855]->[CRITICAL]: 
NoneType: None

[2022-04-28  22:49:59]->[ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:49:59]->[DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:49:59]->[DEBUG]: 
debug
[2022-04-28  22:50:00]->[INFO]: 
info
[2022-04-28  22:50:00]->[WARNING]: 
warning
[2022-04-28  22:50:00]->[ERROR]: 
error
[2022-04-28  22:50:00]->[CRITICAL]: 
critical
[2022-04-28  22:50:00]->[DEBUG]: 
debug
[2022-04-28  22:50:00]->[INFO]: 
info
[2022-04-28  22:50:00]->[WARNING]: 
warning
[2022-04-28  22:50:00]->[ERROR]: 
error
[2022-04-28  22:50:00]->[CRITICAL]: 
critical
[2022-04-28  22:50:00]->[DEBUG]: 
debug
[2022-04-28  22:50:00]->[INFO]: 
info
[2022-04-28  22:50:00]->[WARNING]: 
warning
[2022-04-28  22:50:00]->[ERROR]: 
error
[2022-04-28  22:50:00]->[CRITICAL]: 
critical
[2022-04-28  22:50:00]->[DEBUG]: 
debug
[2022-04-28  22:50:00]->[INFO]: 
info
[2022-04-28  22:50:00]->[WARNING]: 
warning
[2022-04-28  22:50:00]->[ERROR]: 
error
[2022-04-28  22:50:00]->[CRITICAL]: 
critical
[2022-04-28  22:50:00]->[DEBUG]: 
debug
[2022-04-28  22:50:00]->[INFO]: 
info
[2022-04-28  22:50:00]->[WARNING]: 
warning
[2022-04-28  22:50:01]->[ERROR]: 
error
[2022-04-28  22:50:01]->[CRITICAL]: 
critical
[2022-04-28  22:50:01]->[CRITICAL]: 
NoneType: None

[2022-04-28  22:50:25.670]->[ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:50:25.697]->[DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:50:25.911]->[DEBUG]: 
debug
[2022-04-28  22:50:25.960]->[INFO]: 
info
[2022-04-28  22:50:26.100]->[WARNING]: 
warning
[2022-04-28  22:50:26.270]->[ERROR]: 
error
[2022-04-28  22:50:26.277]->[CRITICAL]: 
critical
[2022-04-28  22:50:26.284]->[DEBUG]: 
debug
[2022-04-28  22:50:26.416]->[INFO]: 
info
[2022-04-28  22:50:26.422]->[WARNING]: 
warning
[2022-04-28  22:50:26.608]->[ERROR]: 
error
[2022-04-28  22:50:26.711]->[CRITICAL]: 
critical
[2022-04-28  22:50:26.752]->[DEBUG]: 
debug
[2022-04-28  22:50:26.844]->[INFO]: 
info
[2022-04-28  22:50:26.893]->[WARNING]: 
warning
[2022-04-28  22:50:26.962]->[ERROR]: 
error
[2022-04-28  22:50:26.972]->[CRITICAL]: 
critical
[2022-04-28  22:50:27.080]->[DEBUG]: 
debug
[2022-04-28  22:50:27.151]->[INFO]: 
info
[2022-04-28  22:50:27.206]->[WARNING]: 
warning
[2022-04-28  22:50:27.210]->[ERROR]: 
error
[2022-04-28  22:50:27.214]->[CRITICAL]: 
critical
[2022-04-28  22:50:27.254]->[DEBUG]: 
debug
[2022-04-28  22:50:27.261]->[INFO]: 
info
[2022-04-28  22:50:27.264]->[WARNING]: 
warning
[2022-04-28  22:50:27.266]->[ERROR]: 
error
[2022-04-28  22:50:27.268]->[CRITICAL]: 
critical
[2022-04-28  22:50:27.270]->[CRITICAL]: 
NoneType: None

[2022-04-28  22:52:01.999]->[ERROR]: 
日志等级配置错误，将默认使用DEBUG等级！
[2022-04-28  22:52:02.034]->[DEBUG]: 
日志模块（./src/log.py）配置完毕...
[2022-04-28  22:52:02.057]->[DEBUG]: 
debug
[2022-04-28  22:52:02.072]->[INFO]: 
info
[2022-04-28  22:52:02.081]->[WARNING]: 
warning
[2022-04-28  22:52:02.227]->[ERROR]: 
error
[2022-04-28  22:52:02.233]->[CRITICAL]: 
critical
[2022-04-28  22:52:02.236]->[DEBUG]: 
debug
[2022-04-28  22:52:02.240]->[INFO]: 
info
[2022-04-28  22:52:02.244]->[WARNING]: 
warning
[2022-04-28  22:52:02.414]->[ERROR]: 
error
[2022-04-28  22:52:02.473]->[CRITICAL]: 
critical
[2022-04-28  22:52:02.699]->[DEBUG]: 
debug
[2022-04-28  22:52:02.729]->[INFO]: 
info
[2022-04-28  22:52:02.973]->[WARNING]: 
warning
[2022-04-28  22:52:03.025]->[ERROR]: 
error
[2022-04-28  22:52:03.091]->[CRITICAL]: 
critical
[2022-04-28  22:52:03.338]->[DEBUG]: 
debug
[2022-04-28  22:52:03.408]->[INFO]: 
info
[2022-04-28  22:52:03.457]->[WARNING]: 
warning
[2022-04-28  22:52:03.675]->[ERROR]: 
error
[2022-04-28  22:52:03.758]->[CRITICAL]: 
critical
[2022-04-28  22:52:03.840]->[DEBUG]: 
debug
[2022-04-28  22:52:03.991]->[INFO]: 
info
[2022-04-28  22:52:03.998]->[WARNING]: 
warning
[2022-04-28  22:52:04.000]->[ERROR]: 
error
[2022-04-28  22:52:04.002]->[CRITICAL]: 
critical
[2022-04-28  22:52:04.007]->[CRITICAL]: 
NoneType: None

